# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de8fedecd1b504110a11c307179c8205bceb80bcdd054f3ee1e6ad47358aa56954876c8489defbddef927830234b6cb0044cf5eee7f043b08b39ee6a043f5d8e

test:
  secret_key_base: <%= Settings.get('SECRET_KEY_BASE') %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= Settings.get('SECRET_KEY_BASE') %>
