# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de8fedecd1b504110a11c307179c8205bceb80bcdd054f3ee1e6ad47358aa56954876c8489defbddef927830234b6cb0044cf5eee7f043b08b39ee6a043f5d8e

test:
  secret_key_base: 1929d2cc62dd178aabf70d51b0261897f1d3031c671e72284be6d1bb04d33cb6d024a6d2f3547e789b81f46248c39d0d4e4feacc6951398cc3b040f72e458031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
